---
- hosts: localhost
  gather_facts: no
  ignore_unreachable: yes
  collections:
    - community.vmware
  tasks:
    - name: Power ON
      vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ item }}"
        state: powered-on
        state_change_timeout: 200
      loop: "{{ list_of_vms }}"

    - debug:
        var: shutdown
