---
- hosts: localhost
  gather_facts: no
  ignore_unreachable: yes
  collections:
    - community.vmware
  tasks:
    - name: guest shutdown
      vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ vm_name }}"
        state: shutdown-guest
        state_change_timeout: 120
      register: shutdown
#   - name: Run an executable and send data to the stdin for the executable
#     win_command: powershell.exe Stop-Computer -Force
#     become_user: administrator
#     become_method: runas
