---
- hosts: localhost
  gather_facts: no
  ignore_unreachable: yes
  collections:
    - community.vmware
  tasks:
    - name: guest shutdown 1
      vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ vm_name_1 }}"
        state: shutdown-guest
        state_change_timeout: 200
      register: shutdown_1
      ignore_errors: true
    - name: poweroff 1
      vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ vm_name_1 }}"
        state: powered-off
      when: shutdown_1.failed
      
    - name: guest shutdown 2
      vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ vm_name_2 }}"
        state: shutdown-guest
        state_change_timeout: 200
      register: shutdown_2
      ignore_errors: true
    - name: poweroff 2
      vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ vm_name_2 }}"
        state: powered-off
      when: shutdown_2.failed
      
#   - name: Run an executable and send data to the stdin for the executable
#     win_command: powershell.exe Stop-Computer -Force
#     become_user: administrator
#     become_method: runas
